import numpy as np
arr1 = np.random.rand(4, 4)
arr2 = np.random.rand(4, 4)
abs_arr = np.abs(arr1)
squared_arr = np.square(arr1)
exp_arr = np.exp(arr1)
sin_arr = np.sin(arr1)
sign_arr = np.sign(arr1)
frac_int_parts = np.modf(arr1)
print("16 (модуль):", abs_arr)
print("16 (квадрати елементів):", squared_arr)
print("16 (експоненти елементів):", exp_arr)
print("16 (синуси елементів):", sin_arr)
print("16 (знаки елементів):", sign_arr)
print("16 (дробова та ціла частини):", frac_int_parts)
